# 本文件包含Econ 457 2018年1-4月第三次作业答案程序代码，因无对应作业文档，所以只能提供代码，仅供参考实用。若照抄上交，责任自负。

# The answer of question 1

In [1]:
from scipy.optimize import fsolve
from sympy import *
import numpy as np

def nljac(xvec):
    x = Symbol('x')
    y = Symbol('y')
    
    f1 = 200*x*(y-x**2)-x+1
    f2 = 100*(x**2-y)
    
    result = [
        [diff(f1,x), diff(f1,y)],
        [diff(f2,x), diff(f2,y)]
        ]
    
    f_jac = np.matrix([
        [result[0][0].subs({x : xvec[0], y: xvec[1]}), result[0][1].subs({x:  xvec[0], y: xvec[1] })],
        [result[1][0].subs({x : xvec[0], y: xvec[1]}), result[1][1].subs({x : xvec[0], y: xvec[1] })]
        ],dtype= np.float32)
    #f_jac.astype(np.float32)
    return f_jac
    
 
    
def nlfun(xvec):
    x = Symbol('x')
    y = Symbol('y')
    
    f1 = 200*x*(y-x**2)-x+1
    f2 = 100*(x**2-y)
    
    fval = np.matrix([
        [f1.subs({x: xvec[0] , y: xvec[1] })],
        [f2.subs({x: xvec[0] , y: xvec[1] })]
        ],dtype = np.float32)
    return fval
  
def newton(xvec):
    maxit = 100
    tol = 10*np.exp(-10)
    
    x = xvec
    for it in range(maxit):
        fval = nlfun(x)
        funjac =  nljac(x)
        x = x-np.linalg.inv(funjac).dot(fval)
        if np.linalg.norm(fval)<tol:
            break
    return [x,it+1]
    
def f(xvec):
    x = xvec[0]
    y = xvec[1]
    
    return [
        200*x*(y-x**2)-x+1,
        100*(x**2-y)
        ]
    
    
def check():
    xvec = [1.5,1.5]
    result = fsolve(f,xvec)
    print(result)
    



if __name__ == '__main__':
    
    xvec = np.array([[1.5],[1.5]])
    #xvec = np.mat('1.5;1.5')
    result = newton(xvec)
    print('The iteration time is {0}:'.format(result[1]))
    print('The root is :')
    print(result[0])
    
    
    
    
    #Check the result
    print('\n\n\n')
    print('Root get using scipy.optimize library:')
    check()
    
    
    

    print('****************************Question 1****************************\n')
    print('This is the output of nlfun:')
    print(nlfun(xvec))
    print('\n')
    
    print('This is the output of nljac:')
    print(nljac(xvec))
    #print(np.linalg.inv(fjac(xvec)))
    print('\n')


    

The iteration time is 5:
The root is :
[[1.]
 [1.]]




Root get using scipy.optimize library:
[1. 1.]
****************************Question 1****************************

This is the output of nlfun:
[[-225.5]
 [  75. ]]


This is the output of nljac:
[[-1051.   300.]
 [  300.  -100.]]




# The answer of question 2

In [2]:
from scipy.optimize import fsolve
from sympy import *
import numpy as np


def f(xvec):
    x = xvec[0]
    y = xvec[1]
    
    s = 3
    k = 0.2
    thelta = 0.95
    return [
        x+k-thelta*y,
        s-np.power(x,-1/5)-np.power(y,-1/5)
        ]
    
    
def check(f):
    xvec = [2.7,1.5]
    result = fsolve(f,xvec)
    print(result)
    



def fjac(xvec,s,k,thelta):
    x = Symbol('x')
    y = Symbol('y')
    
    f1 = x+k-thelta*y
    f2 = s-np.power(x**(-1),1/5)-np.power(y**(-1),1/5)
    
    result = [
        [diff(f1,x), diff(f1,y)],
        [diff(f2,x), diff(f2,y)]
        ]
    

    f_jac = np.matrix([
      [result[0][0].subs({x : xvec[0], y: xvec[1]}), result[0][1].subs({x:  xvec[0], y: xvec[1] })],
      [result[1][0].subs({x : xvec[0], y: xvec[1]}), result[1][1].subs({x : xvec[0], y: xvec[1] })]
      ],dtype= np.float32)

    return f_jac
    
 
    
def nlfun(xvec,s,k,thelta):
    x = Symbol('x')
    y = Symbol('y')
    
    f1 = x+k-thelta*y
    f2 = s-np.power(x**(-1),1/5)-np.power(y**(-1),1/5)
    
    fval = np.matrix([
        [f1.subs({x: xvec[0] , y: xvec[1] })],
        [f2.subs({x: xvec[0] , y: xvec[1] })]
        ],dtype = np.float32)
    return fval
  
def newton(xvec,s,k,thelta):
    maxit = 1000
    tol = 10*np.exp(-10)
    
    x = xvec
    for it in range(maxit):
        fval = nlfun(x,s,k,thelta)
        funjac =  fjac(x,s,k,thelta)
        x = x-np.linalg.inv(funjac).dot(fval)
        if np.linalg.norm(fval)<tol:
            break
        
    print('The iteration time is {0}'.format(it+1))
    print('The root [p1*, p2*] is :')
    print(x)
    print('\n')
    #return [x,it+1]
    
    
    

if __name__ == '__main__':
    
    xvec = xvec = np.array([[1.5],[1.5]])
    s1 = 1
    s2 = 2
    s3 = 3
    k1 = 0.1
    k2=0.2
    thelta1 = 0.95
    thelta2 = 0.5
    
    
    check(f)
    
    

    print('For question part (a):')
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s1,k2,thelta1))
    newton(xvec,s1,k2,thelta1)
   
    
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s2,k2,thelta1))
    newton(xvec,s2,k2,thelta1)
   
    '''
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s3,k2,thelta1))
    newton(xvec,s3,k2,thelta1)
    print('\n')
    
    '''
    
    
    print('For question part (b):')
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s1,k1,thelta1))
    newton(xvec,s1,k1,thelta1)
    
    
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s2,k1,thelta1))
    newton(xvec,s2,k1,thelta1)
    
    '''
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s3,k1,thelta1))
    newton(xvec,s3,k1,thelta1)
    print('\n')
    '''
    
    
    print('For question part (c):')
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s1,k2,thelta2))
    newton(xvec,s1,k2,thelta2)
    
    
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s2,k2,thelta2))
    newton(xvec,s2,k2,thelta2)
   
   
    '''
    print('When the parameters are: s = {0}, k = {1}, thelta = {2}'.format(s3,k2,thelta2))
    newton(xvec,s3,k2,thelta2)
    print('\n')
    
    '''
    
    

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app
/opt/conda/lib/python3.6/site-packages/scipy/optimize/minpack.py:163: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


[2.7 1.5]
For question part (a):
When the parameters are: s = 1, k = 0.2, thelta = 0.95
The iteration time is 6
The root [p1*, p2*] is :
[[31.09246298]
 [32.93943471]]


When the parameters are: s = 2, k = 0.2, thelta = 0.95
The iteration time is 4
The root [p1*, p2*] is :
[[0.88138309]
 [1.13829799]]


For question part (b):
When the parameters are: s = 1, k = 0.1, thelta = 0.95
The iteration time is 6
The root [p1*, p2*] is :
[[31.14206246]
 [32.88638153]]


When the parameters are: s = 2, k = 0.1, thelta = 0.95
The iteration time is 4
The root [p1*, p2*] is :
[[0.92653673]
 [1.08056498]]


For question part (c):
When the parameters are: s = 1, k = 0.2, thelta = 0.5
The iteration time is 6
The root [p1*, p2*] is :
[[22.80774772]
 [46.01549544]]


When the parameters are: s = 2, k = 0.2, thelta = 0.5
The iteration time is 5
The root [p1*, p2*] is :
[[0.63073506]
 [1.66147012]]


